kind: pipeline
name: default

steps:
- name: Drone
  image: ubuntu
  commands: |
    apt update
    apt install -y git python3 python3-pip
    git submodule update --init --recursive
    python3 -m pip install --upgrade pip
    pip3 install -U https://github.com/platformio/platformio/archive/develop.zip
    platformio platform install file://.
    platformio run -d examples/zephyr-blink
    platformio run -d examples/arduino-blink
