build: off
environment:

  matrix:
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/libopencm3"
    - PLATFORMIO_PROJECT_DIR: "examples/spl-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-external-libs"
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-internal-libs"
    - PLATFORMIO_PROJECT_DIR: "tests/arduino-blink-different-cores"
    - PLATFORMIO_PROJECT_DIR: "tests/mbed-filesystem"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-custom-target"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-dsp"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-events"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-filesystem"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-rtos"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-rtos-ethernet"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-rtos-ethernet-tls"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-rtos-semaphore"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-rtos-mesh-minimal"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-serial"
    - PLATFORMIO_PROJECT_DIR: "examples/stm32cube-hal-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/stm32cube-ll-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/zephyr-blink"


install:
  - cmd: git submodule update --init --recursive
  - cmd: SET PATH=C:\Python36\Scripts;%PATH%
  - cmd: pip3 install -U https://github.com/platformio/platformio/archive/develop.zip
  - cmd: platformio platform install file://.

test_script:
  - cmd: platformio run -s -d %PLATFORMIO_PROJECT_DIR%

