version: 2
jobs:

  QIO:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: "Install"
          command: |
            apt update
            apt install -y git
            git submodule update --init --recursive
            python -m pip install --upgrade pip
            pip install -U https://github.com/OS-Q/M03/releases/latest/download/qio.zip
            qio platform install file://.
      - run:
          name: "Build"
          command: |
            pio run -d examples/arduino-blink
            pio run -d examples/cmsis-blink
            pio run -d examples/spl-blink
            pio run -d examples/mbed-blink
            pio run -d examples/stm32cube-hal-blink
            pio run -d examples/stm32cube-ll-blink

workflows:
    version: 2
    run_ci:
        jobs:
          - QIO

