name: CD

on:
  push:
    tags:
      - 'v*'


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    if: github.repository == 'OS-Q/P21'
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.9]
        examples:
          - "examples/arduino-blink"
          - "examples/cmsis-blink"
          - "examples/libopencm3-blink"
          - "examples/spl-blink"
          - "examples/stm32cube-hal-blink"
          - "examples/stm32cube-ll-blink"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/archive/master.zip
          qio platform install file://.

      - name: Build
        run: |
          qio run -d ${{ matrix.examples }}

  release:
    needs:
      - build
    if: success() && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Generate tag
        id: tag
        if: startsWith(github.ref, 'refs/tags/') && steps.build.outputs.status == 'success' && !cancelled()
        run: |
          echo "::set-output name=release_tag::Release_${GITHUB_REF/refs\/tags\//}_$(date +"%Y.%m.%d")"
          echo "::set-output name=status::success"

      - name: package
        id: package
        run: |
          zip -r P21.zip boards builder link.json
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV

      - name: Upload Release
        id: upload-release
        uses: stopstopstop/release-action@master
        if: steps.tag.outputs.status == 'success' && !cancelled()
        env:
          GITHUB_TOKEN: ${{ secrets.OSQ_REPO_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            ${{ env.FIRMWARE }}/P21.zip

  deploy:
    needs:
      - release
    if: success() && needs.release.result != 'skipped'
    runs-on: ubuntu-latest

    steps:
      - name: upload
        uses: stopstopstop/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.SSHPORT }}
          script: |
            cd /home/www/html/package
            wget https://github.com/OS-Q/P21/releases/latest/download/P21.zip -O P21.zip
